import Head from "next/head";
import Convert from "../components/Convert";

export default function App() {
  return (
    <div>
      <Head>
        <title>Convertium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Convert />
    </div>
  );
}
